spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintechTest
    username: root
    password:

    jpa:
      hibernate:
        ddl-auto: update

    servlet:
      multipart:
        enabled: true

    security:
      user:
        name: achraf
        password: achraf

    data:
      rest:
        base-path: /rest
